# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '$directory$character'
right_format = """
$cmd_duration\
$container\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$ruby\
$golang\
$elixir\
$docker_context\
"""

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_metrics]
# disabled = false

[nodejs]
format = '[$symbol($version )]($style)'

[ruby]
format = '[$symbol($version )]($style)'
